backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "CV Internal"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Firstname", name: "firstname", widget: "string" }
      - { label: "Lastname", name: "lastname", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Languages", name: "languages", widget: "string" }
      - { label: "Education", name: "education", widget: "string" }
      - { label: "Birthday", name: "birthday", widget: "datetime" }
      - {
          label: "Work experience since",
          name: "workexperience",
          widget: "datetime",
        }
      - { label: "Image", name: "image", widget: image }
      - { label: "Experiences", name: "experiences", widget: "text" }
      - {
          label: Projects,
          name: projects,
          widget: object,
          fields:
            [
              {
                label: Projects,
                name: projects,
                widget: list,
                fields:
                  [
                    { label: Visible, name: visible, widget: boolean },
                    { label: Projectname, name: project, widget: text },
                    { label: Duration, name: duration, widget: text },
                    { label: Text, name: text, widget: text },
                  ],
              },
            ],
        }
